services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    volumes:
      # conf files
      - ./nginx.conf:/etc/nginx/nginx.conf
      # SSL certs
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      # logs
      - ./data/nginx/logs:/var/log/nginx
      # optional confs
      # Easy websocket config
      # Global settings
      # for hosts behind Cloudflare Tunnel
      # HTTP Strict Transport Security (HSTS)
      - ./conf.d:/etc/nginx/conf.d            
      

# if not running on host network, expose ports      
#    ports:
#      - "80:80"
#      - "443:443"
    depends_on:
      - certbot

  certbot:
    image: certbot/dns-cloudflare  # Certbot with Cloudflare DNS plugin
    container_name: certbot
    network_mode: "host"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./cloudflare.ini:/etc/letsencrypt/cloudflare.ini  # Cloudflare credentials
    
    # while loop is not necessary if you create a server and timer on the host 
    entrypoint: >
      /bin/sh -c "
      certbot certonly --non-interactive --quiet --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini \
      --email ${EMAIL} --agree-tos --no-eff-email --expand \
      --domains ${DOMAINS};
     
      while :; do 
        certbot renew --non-interactive --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini;
        sleep 24h;
      done
      "
